config/routes.rb
Rails.application.routes.draw do

  root "posts#index"
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  # Patients route
  resources :patients

  # get '/patients/names', to: 'patients#patient_names', as: 'patient_names'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/patient.rb
class Patient < ApplicationRecord
  validates :name, presence: true
  validates :age, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :email, presence: true, format: { with: /\A\S+@\S+\.\S+\z/ }
  validates :address, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  def index
    # @patients = Patient.all

    # Using kaminari paginate
    @patients = Patient.page(params[:page]).per(10)
  end

  def show
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)

    if @patient.save
      redirect_to @patient, notice: 'Patient was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @patient.update(patient_params)
      redirect_to @patient, notice: 'Patient was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @patient.destroy
    redirect_to patients_url, notice: 'Patient was successfully destroyed.'
  end

  private

  def set_patient
    if params[:id].to_i.to_s == params[:id]
      # If params[:id] is an integer, treat it as an ID
      @patient = Patient.find(params[:id])
    else
      # If params[:id] is not an integer, treat it as a name
      @patient = Patient.find_by(name: params[:id])
    end
    # Ensure that the patient is found before attempting to destroy
    raise ActiveRecord::RecordNotFound unless @patient
  end


  def patient_params
    params.require(:patient).permit(:name, :age, :email, :address)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }

        # using turbo
        format.turbo_stream { render :create, locals: { post: @posts } }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }

        format.turbo_stream { render :new, status: :unprocessable_entity, locals: { post: @posts } }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoutePractice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/patients/_form.html.erb
<%= form_with(model: @patient, local: true) do |form| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
        <% @patient.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, placeholder: 'Enter your name' %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age, placeholder: 'Enter your age' %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email, placeholder: 'Enter your email' %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, placeholder: 'Enter your address' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/patients/_patient.html.erb
<!-- app/views/patients/_patient.html.erb -->
<tr>
  <%# Connecting HTML with JS and adding a target and action using Stimulus %>
  <td data-controller="patient-name" data-patient-name-target="name" data-action="click->patient-name#getName"><%= patient.name %></td>
  <td><%= patient.age %></td>
  <td><%= patient.email %></td>
  <td><%= patient.address %></td>
  <%= render partial: 'patient_links', locals: { patient: patient } %>
</tr>

app/views/patients/_patient_links.html.erb
<!-- app/views/patients/_patient_links.html.erb -->
<td><%= link_to 'Show', patient_path(patient), class: 'view-link' %></td>
<td><%= link_to 'Edit', edit_patient_path(patient), class: 'edit-link' %></td>
<td><%= link_to 'Destroy', patient_path(patient), class: 'destroy-link', data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %></td>

app/views/patients/edit.html.erb
<h1>Edit Patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<% cache('patients_index', expires_in: 1.minutes) do %>
  <h1>Patients</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Age</th>
        <th>Email</th>
        <th>Address</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% if @patients.empty? %>
        <tr>
          <td colspan="4">No patients exist.</td>
        </tr>
      <% else %>
        <%= render partial: 'patients/patient', collection: @patients %>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Patient', new_patient_path %>

  <%= paginate @patients %>
<% end %>

<%# Reading a cache %>
<%# Rails.cache.read('patients_index') %>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form' %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @patient.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @patient.age %>
</p>

<p>
  <strong>Email:</strong>
  <%= @patient.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @patient.address %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>

app/views/people/index.html.erb
<h1>Names of all the patients</h1>
<% @patients.each do |patient| %>
  Name: <%= patient.name %><br>
<% end %>

<%# Steps to render HTML in console %>

<%# @patients = Patient.all %>
<%# rendered_html = ApplicationController.render(template: 'people/index', assigns: { patients: @patients }) %>
<%# puts rendered_html %>

app/views/posts/_form.html.erb
<%= turbo_frame_tag "new_post" do %>

<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= post.content %>
  </p>

</div>

app/views/posts/create.turbo_stream.erb
<%= turbo_stream.prepend "posts" do %>
  <%= render partial: "post", locals: { post: @post } %>
<% end %>

<%= turbo_stream.replace "new_post",
partial: "form",
locals: { post: Post.new } %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<h2>New Post</h2>
<%= render "form", post: Post.new %>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/new.turbo_stream.erb
<%= turbo_stream.replace "new_post" do %>
  <%= render partial: "form", locals: { post: @post } %>
<% end %>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>